(lang dune 3.20)

(name adventofcode2025)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Julian Köpke <root@j4nk.dev>")

(maintainers "Julian Köpke <root@j4nk.dev>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name adventofcode2025)
 (synopsis "Advent of Code 2025")
 (description "Advent of Code 2025 solutions in OCaml 🐫")
 (depends ocaml)
 (tags ("adventofcode")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
